name: slither
on:
  pull_request:
    branches:
      - main
jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Slither
        uses: crytic/slither-action@v0.4.1
        continue-on-error: true
        id: slither
        with:
          fail-on: none
          target: "src/"
